/*
 * This file is part of the Skycoin project, https://skycoin.net/
 *
 * Copyright (C) 2018-2019 Skycoin Project
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 */

// Autogenerated from https://github.com/skycoin/skycoin/tree/7cc25f1cb91afe5220a2bbc2ca93177d6a91c2a0/
// WARNING: Do not edit

#ifndef __TEST_SEED_0000_GOLDEN__

#define TEST_SEED_0000_SEED "wire junk original sword bread bottom armor dog snow accident inform rigid"

extern char TEST_SEED_0000_ADDRESSES[10][37];
extern char TEST_SEED_0000_BITCOIN_ADDRESSES[10][37];
extern char TEST_SEED_0000_SECRETS[10][65];
extern char TEST_SEED_0000_PUBLICS[10][67];

#endif // __TEST_SEED_0000_GOLDEN__
