// This file is automatically generated from coin_info.h.mako
// DO NOT EDIT

#ifndef __BITCOIN_H__
#define __BITCOIN_H__

#include "coins.h"

#define COINS_COUNT (1)

extern const CoinInfo coins[COINS_COUNT];

#endif
